language: python
python:
  - "3.6"
install:
  - pip install http://download.pytorch.org/whl/cu80/torch-0.2.0.post1-cp35-cp35m-manylinux1_x86_64.whl
  - pip install torchvision pytest pytest-cov coveralls
  - pip install -e .
script:
  - pytest tests --cov=pytorch_unet
after_success:
  - coveralls
